
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true

  Exclude:
    - 'db/schema.rb'
    - 'config/application.rb'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'config/initializers/assets.rb'
    - 'bin/setup'
    - 'db/migrate/20141004030325_devise_create_users.rb'
    - 'config/**/*'
    - 'config.ru'
    - 'Rakefile'
    - 'spec/teaspoon_env.rb'

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/integration/*'

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
