language: ruby
rvm:
- 2.0.0
script:
- psql -c 'create database pixel_paisan_test_postgres;' -U postgres
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
bundler_args: --binstubs=./bundler_stubs
deploy:
  provider: heroku
  api_key:
    secure: BwEotIJty3w34ACxW+8/zft7Npi7NOzm4fkUr1puZad7yrqqDhvRZQjrhO6wqvxGhHR0Rkw7y2BzwV4WdcBkNcL4msZ5OSSRiJcqqdqsxHG28KgmD+JSkIvmVF4TuJgteTgfT20Lq/H97Os4JKQaIekoxWRFtoj8nhhwi27LmXc=
  app: pixel-paisan
  on:
    repo: nbarnes/pixel_paisan
  run:
  - rake db:migrate
